Help for %sub%'s newsletter bot!
Hi %user%!

I'm just here to show you what you can do!

Not yet subscribed? You can **subscribe** by sending me [this](http://www.reddit.com/message/compose/?to=subnewsbot&subject=subscribe&message=i%20wanna%20subscribe!).

If you want to **list** all previous issues, send me [this](http://www.reddit.com/message/compose/?to=subnewsbot&subject=get&message=i%20wanna%20see%20all%20the%20issues!)

If you want to **get** any of these previous issues, send me [this](http://www.reddit.com/message/compose/?to=subnewsbot&subject=get&message=issue%20names%20seperated%20by%20commas).

You want to leave? You can **unsubscribe** by sending me [this](http://www.reddit.com/message/compose/?to=subnewsbot&subject=unsubscribe&message=i%20wanna%20get%20the%20hell%20off%20this%20list!).

%signature%