List of %sub%'s issues!
Hi %user%!

I'm just here to list you all of %sub%'s newletters names!

%list%

If you want to **get** any of these previous issues, send me [this](http://www.reddit.com/message/compose/?to=subnewsbot&subject=get&message=issue%20names%20seperated%20by%20commas).

Is this a mistake? You can **unsubscribe** by sending me [this](http://www.reddit.com/message/compose/?to=subnewsbot&subject=unsubscribe&message=i%20wanna%20get%20the%20hell%20off%20this%20list!).

%signature%