Subscribed to %sub%'s newsletter!
Hi %user%!

I'm just here to tell you that you've succesfully subscribed to %sub%'s newletter! You should automatically receive the next issue.

If you want to **get** previous issues, send me [this](http://www.reddit.com/message/compose/?to=subnewsbot&subject=get&message=issue%20names%20seperated%20by%20commas).

If you want to **list** all previous issues, send me [this](http://www.reddit.com/message/compose/?to=subnewsbot&subject=get&message=i%20wanna%20see%20all%20the%20issues!)

Is this a mistake? You can **unsubscribe** by sending me [this](http://www.reddit.com/message/compose/?to=subnewsbot&subject=unsubscribe&message=i%20wanna%20get%20the%20hell%20off%20this%20list!).

%signature%